global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:6004']

  - job_name: 'mediator-service'
    static_configs:
      - targets: ['mediator-service:6001']

  - job_name: 'data-service'
    static_configs:
      - targets: ['data-service:6002']
